### ISSUE TITLE
Incorporate ofxiOSBoost

### ISSUE THREAD

**Issue by danoli3** [danomatika/ofxLua#23]
Hey @danomatika, you should think about incorporating ofxiOSBoost in the readme for iOS Boost dependancy.

https://github.com/danoli3/ofxiOSBoost

I've received a few e-mails from people setting up ofxLua and if ofxiOSBoost would work for it.

**Comment by danoli3** [comment]
Actually while we are here, maybe a good idea for https://github.com/danoli3/ofxOSXBoost as well... 
https://github.com/danoli3/ofxCGAL uses this well.

**Comment by danomatika** [comment]
No worries. I've replaced Luabind with SWIG in the `swig` branch which will become master in the near future. Boost was always a necessary evil to use Luabind but I think SWIG is the better long term option.

**Comment by danoli3** [comment]
Oh nice! Very nice decoupling! I'll be trying out your swig branch :)

**Comment by danomatika** [comment]
Thanks. With Boost on OS X, I found it easier to just use Homebrew. That way you don;t need to manager version of Boost itself. Naturally, iOS is a different story which is why I'm glad I got SWIG to work. It should also make building dynamic modules easy (I'll try that next).
