### ISSUE TITLE
Create a New ofxLua Project failed

### ISSUE THREAD

**Issue by igoumeninja** [danomatika/ofxLua#24]
Hi Dan, I try to develop my own project based on ofxLua, simply copy an example project and rename it at 3 levels down in the openframeworks folder, but I am taking the error:

![screen shot 2015-03-27 at 1 29 39 pm](https://cloud.githubusercontent.com/assets/155644/6866908/689a7d80-d485-11e4-8abb-85cbf2a4fab9.png)
Any help?
Thanks in advance.

**Comment by danomatika** [comment]
2 things:

1. I've moved from Luabind to using SWIG to generate the Lua bindings which means ofxLua now works with the Project Generator. It's currently in the [swig branch](https://github.com/danomatika/ofxLua/tree/swig), but I will make that branch master very soon (perhaps today).
2. That error says "no such file or directory: '....../apps/GEA/src/bindings/Gl.cpp'" which means you probably forgot to add the files in that directory to your project.

**Comment by igoumeninja** [comment]
Thanks Dan, I will try swig branch.

**Comment by danomatika** [comment]
Gimme a minute. I'm going to make swig the master branch now since that's what I've been using for a while now.

**Comment by igoumeninja** [comment]
Sorry Dan! All the time you want.

**Comment by danomatika** [comment]
I've been meaning do it anyway. The master branch is now up to date. The previous master is now the "luabind" branch if you have any projects that rely on luabind.

**Comment by igoumeninja** [comment]
I check it with project generator and is working like a charm. Thanks
