### ISSUE TITLE
Create your own binding with swig

### ISSUE THREAD

**Issue by igoumeninja** [danomatika/ofxLua#25]
Hi Dan, again,
I am trying to create my own binding by following your instruction. I am taking the following errors:
![screen shot 2015-03-27 at 7 54 00 pm](https://cloud.githubusercontent.com/assets/155644/6873734/095528d0-d4bb-11e4-9055-4f973e0bae1e.png)

The project is here: https://github.com/igoumeninja/Gea/tree/working_branch
If you find some time to help, I 'll be greattful.
Thanks in advance

**Comment by danomatika** [comment]
Add "#include "MyCode.h" to the top of your interface file and regenerate the bindings:

    %module my
    %{
        // include any needed headers here
        #include "ofMain.h"
        #include "MyCode.h"
    %}

Also, you may not need to include ofMain.h if you're not using any openFrameworks classes, functions, etc.

**Comment by danomatika** [comment]
Also, you'll need to create an implementation for those functions & class methods. The example code is not actually tested.

**Comment by danomatika** [comment]
I updated the example which should actually compile now.

**Comment by igoumeninja** [comment]
Thanks again Dan, there is typographical error at 
```
            aString = "hello world"i;
```
an extra i.

**Comment by danomatika** [comment]
I fixed it already. Lots of typos, should be fine now.

**Comment by igoumeninja** [comment]
It's working. 
Thanks again and greetings from Greece.

**Comment by igoumeninja** [comment]
Something more Dan, although the project has a successful compile with the following lua script:
```

function setup()
   of.setWindowTitle("startUp")
   of.background(0)

   aNumber = my.function(3.45)

end
----------------------------------------------------
function update()

end
----------------------------------------------------
function draw()
   of.fill()
   of.setColor(0,0,0,20)
   of.rect(0,0,of.getWidth(), of.getHeight())

   of.setColor(250,230,230,230)
   of.rect(100,100,100,20)
end
----------------------------------------------------
function keyPressed(key)
   if key == string.byte("s") then
   end
end
```
I am taking the error:
```
[notice ] got a script error: ...sx_release/apps/GEA/gea_swig/bin/data/scripts/my-lua-scripts/startup.lua:6: '<name>' expected near 'function' 
```

**Comment by danomatika** [comment]
Might be because the function name is wrong. It's actually: "my.myFunction" and the class constructor is "my.MyCoolClass". I'll update the example.

**Comment by igoumeninja** [comment]
Change to
```
   aNumber = my.myFunction(3.45)
```
taking the result:
```
[notice ] got a script error: Error running setup(): ...gea_swig/bin/data/scripts/my-lua-scripts/startup.lua:6: attempt to index global 'my' (a nil value)
[verbose] ofxLua: Cleared state
```

**Comment by danomatika** [comment]
Did you open your custom lua lib after initing the lau state? You have to do this every time you call init(). https://github.com/danomatika/ofxLua#opening-your-lua-library

**Comment by igoumeninja** [comment]
Yes, here is my ofApp.cpp file https://github.com/igoumeninja/Gea/blob/working_branch/src/ofApp.cpp.

**Comment by danomatika** [comment]
But not after this one: https://github.com/igoumeninja/Gea/blob/working_branch/src/ofApp.cpp#L37 :D Calling init() again completely clears the state.

**Comment by danomatika** [comment]
... or here: https://github.com/igoumeninja/Gea/blob/working_branch/src/ofApp.cpp#L125

**Comment by igoumeninja** [comment]
I add 
```
 luaopen_my(lua);
```
at positions, but still got an error.
```
[notice ] got a script error: Error running setup(): ...gea_swig/bin/data/scripts/my-lua-scripts/startup.lua:4: attempt to call field 'myFunction' (a nil value)
[verbose] ofxLua: Cleared state
```

**Comment by danomatika** [comment]
You broke it here: https://github.com/igoumeninja/Gea/blob/working_branch/src/MyBindings.i

My earlier comment about adding the #include "MyCode.h" line didn't mean to replace all of the text with that, you still need to run the `%include "MyCode.h"` which actually tells SWIG what it should generate bindings. As you gave it now, you only tell SWIG you want to create a "my" lua module but nothing else.

As it says in my readme updates, your interface file should contain this:

    %module my
    %{
        // include any needed headers here
        #include "MyCode.h"
    %}
    
    // include custom code you want to be wrapped,
    // note the '%' instead of '#' as '%include' is a SWIG
    // command to wrap code in the given header
    %include "MyCode.h"

**Comment by danomatika** [comment]
You can check what's loaded in the lua state by printing all the tables after init() and luaopen_my: `lua.printTable()".

**Comment by igoumeninja** [comment]
I change the MyBindings.i file, run ```swig -c++ -lua -fcompact -fvirtual -I../../../libs/openFrameworks MyBindings.i``` and getting the error:
![screen shot 2015-03-27 at 9 46 35 pm](https://cloud.githubusercontent.com/assets/155644/6875819/c27546ce-d4ca-11e4-98e3-c09009d08e54.png)

**Comment by danomatika** [comment]
Remove `#include "MyCode.h"` from ofApp.h.

**Comment by igoumeninja** [comment]
DONE, thanks a lot Dan. Have a nice evening. I getting out to a concert: https://www.youtube.com/watch?v=TfoisYwKAVg. Have a nice day!

**Comment by danomatika** [comment]
There's one last thing you'll need to update. See the latest version of the example MyBindings.i in https://github.com/danomatika/ofxLua#swig-interface

I forgot to add the %includes SWIG needs in order to correctly handle std::string conversion to lua strings. I tested with you're code and the example now works correctly. Thanks for going through this so we know it works.
