### ISSUE TITLE
[REQUEST] to remove 'script' on functions

### ISSUE THREAD

**Issue by lewislepton** [danomatika/ofxLua#26]
really getting into ofxLua, want to use it fully for game making within openFrameworks, so thanks.

one thing i would like to request is that instead of having say 'lua.scriptSetup() or lua.scriptUpdate(), how about just having lua.update()/ lua.setup() / lua.draw() etc. just more to stay in tune with openframeworks. it would also be less confusing.

i understand why to some degree but think that would help

thanks

**Comment by danomatika** [comment]
The original idea was that people might inherit the ofxLua class, so using the script* naming made sure there e'rent any conflicts. I think it's true, that at this point, nobody is really using it that way, so I could make that change. Let me double check first though.

**Comment by lewislepton** [comment]
thats cool man. if not then im cool, but cool if it could be more openframeworks based in that fashion of naming.

thanks again.

one more thing to add. could ofxLua inherit ofxGui things like sliders/buttons/toggles? just as a side question to not open another question ;)

thanks

**Comment by lewislepton** [comment]
and i have been 'ummming' and 'ahhhing' at finding something to use lua in for games. found some nice binders for lua and sdl. but might see if i can just use ofxLua with openframeworks instead, since i know both lua and openframeworks. thanks again for this ;)

**Comment by danomatika** [comment]
After looking at the API again, I think it should stay. "setup()", "update()", "draw()", etc are a little ambiguous by themselves as in "what's being setup()?", "what's being drawn()?", etc. "scriptDraw()" makes it much more obvious that you are calling the draw function in the lua state aka script. Also, there is an init() function ... it would be a bit confusing having both"init()" and "setup()" as well as "clear()" and "exit()". Again, prepending with "script" cuts out the ambiguities. Sure, all the functions can be commented but things should be named intuitively.

**Comment by lewislepton** [comment]
thats cool, no worries and understandable. thanks anyhow
