### ISSUE TITLE
[QUESTION] using classes

### ISSUE THREAD

**Issue by lewislepton** [danomatika/ofxLua#27]
im just working with using classes. having a main.lua which deals in the main brunt of bringing all the other .lua files together, and then have my other game .lua files. but on trying this many different ways, it does not seem to be working. im guessing that using something like of.Image within a class is not allowed, but know this to be false.

here is my main.lua, then my playerClass.lua im making. could you just point out what is wrong. i have been through the lua stuff plus what you had said on the github page, but its just not working for me.
im just not seeing the problem sadly

thanks

main.lua
```
PlayerClass = require 'PlayerClass'

function setup()
	PlayerClass:setup()
end

function update()
	-- body
end

function draw()
	PlayerClass:draw()
end
```

PlayerClass.lua
```
PlayerClass = class()
image = of.Image()
function PlayerClass:setup()
	image:loadImage('sprite/player/Player.png')
end

function PlayerClass:update()
	-- body
end

function PlayerClass:draw()
	image:draw(0,0)
end
```

**Comment by lewislepton** [comment]
i also just doubled check again to see if it was because my code is within a folder also, and did change the location, but no. bit strange

**Comment by danomatika** [comment]
That won't work by default because the current working path is the folder where the compiled program is. You can either include a relative path in the require statement or, better yet, change directory to where the main script currently is so the require works as expected (the following is form my Visual app):

    // change the current dir to the scene directory,
    // this allows the lua state to find local files
    string path = ofFilePath::getEnclosingDirectory(script);
    if(!ofDirectory::doesDirectoryExist(path)) {
        ofLogError() << "ScriptEngine: script dir \"" << path << "\" does not exist";
        return;
    }
    else {
        if(chdir(path.c_str()) != 0) {
            ofLogError() << "ScriptEngine: couldn't change directory to \"" << path << "\"";
            return;
        }
    }

**Comment by lewislepton** [comment]
fantastic, ill just give that a go. guess im just used to what original lua is like ;)

**Comment by lewislepton** [comment]
so just to grasp this slightly more.
where does this relocation code go? does it go with the ofApp.cpp, which im thinking since that is the main setup ofxLua.
i did try it in update and also draw, but there are problems due to the 'script' being in a vector in the .h file.

again, thanks for your help

**Comment by danomatika** [comment]
"Original" Lua is the interpreter which runs using the current directory. All we have to do is replace that behavior, as I've mentioned. Nothing fancy about it.

If you're only loading the main script once, put it in setup(). If you need to be able to reload the script when the app is running, put it in the reload function after before calling doScript. I'll add this to the examples.

**Comment by danomatika** [comment]
On second thought, I will add this as an option to doScript so it's built in. That should make things easy.

**Comment by lewislepton** [comment]
thanks. does mean a lot this. just a bit confusing sometimes ;)

**Comment by danomatika** [comment]
Add this in your setup() to see how OF is actually handling things:

    ofLog() << ofFilePath::getCurrentWorkingDirectory();

Calling ofToDataPath helps take care of where things are, but does not change the current working directory.

**Comment by lewislepton** [comment]
ok. but that ofDirectory if statement from is still not sinking in. sorry.
the whole OF handling was great, so thank you for.
ill wait to see what the examples can tell me i guess

**Comment by danomatika** [comment]
Knowledge is power.

On Mac OSX, an OF app starts with this current working dir (relative to inside the app bundle):

    ../../../data

which means "go up 3 levels and then into the data folder" since the layout is:

    YourApp
        /bin
            /data <--- your data is here
            /YourApp.app <--- this is the Mac OS app which is actually just a folder with an icon
                /Contents
                    /MacOS
                        YourApp <---- this is the actual program hidden inside the Mac OS app bundle
                    /Resources <--- some app resources are here like the icon & info property list
        /src
        /YourApp.xcodeproj

So the current working directory for this example (relative to the open frameworks/apps folder) would be:

    YourApp/bin/YourApp.app/Contents/MacOS

Similarly, the data directory is actually at:

    YourApp/bin/data

and the relative data path is:

    ../../../data

So it's kind of like math:

      YourApp/bin/YourApp.app/Contents/MacOS
                    - ../                 - ../           - ../             + data
    ----------------------------------------------------------------------
    = YourApp/bin/data

This is why loading an image etc "just works" in OF, since the data path is appending to the given filename. Even though the current working dir is in a different place, the data path handles that for you.

So the main problem with the lua situation is that your scripts are in the data dir but Lua does't know anything about how ofToDataPath works, so it's trying to load names in `require` for the **current working dir** which is *not* the data path but where the app is:

    YourApp/bin/data/scriptA.lua
    YourApp/bin/data/scriptB.lua

scriptA.lua:

    require "scriptB"

This does't work since lua is actually searching for it like this:

    YourApp/bin/YourApp.app/Contents/MacOS/scriptB.lua

We can fix that by literally changing the current working directory to the location of the script:

    cd to YourApp/bin/data

Now it will work, since now lua will reach like this:

    YourApp/bin/data/scriptB.lua

**Comment by lewislepton** [comment]
thans for the explaination and the help
with my lua file, which is my main.lua, this should be now importing my PlayerClass.lua

main.lua
```
PlayerClass = require('AppDebug.app/bin/data/PlayerClass.lua')
function setup()
	PlayerClass.setup()
	-- image:loadImage('sprite/player/Player.png')
end

function draw()
	PlayerClass.draw()
	-- image:draw(0,0)
end
```

and this now the PlayerClass.lua
```
PlayerClass = {}

image = of.Image()

function PlayerClass.setup()
	image:loadImage('sprite/player/Player.png')
end

function PlayerClass.draw()
	image:draw(0,0)
end
```

**Comment by danomatika** [comment]
Right. That's one way to do it. I've added code to change the dir so manually adding the path shouldn't be required.

**Comment by lewislepton** [comment]
or to expand. were you more thinking on with ofApp.cpp to be this
```
script.push_back("AppDebug.app/bin/data/code/main.lua");
```

**Comment by lewislepton** [comment]
i have actually ran the code. the last one with both the main.lua and playerclass.lua
and have in my ofApp.cpp this:
```
//--------------------------------------------------------------
void VERMONT::setup(){
    ofSetVerticalSync(true);
    ofSetFrameRate(60);
    script.push_back("code/VERMONT.lua");
    lua.init();
    lua.doScript(script[currentScript]);
    lua.scriptSetup();
}

//--------------------------------------------------------------
void VERMONT::update(){
    lua.scriptUpdate();
}

//--------------------------------------------------------------
void VERMONT::draw(){
    lua.scriptDraw();
}
```
main.lua
```
PlayerClass = require('AppDebug.app/bin/data/PlayerClass.lua')
function setup()
	PlayerClass.setup()
end

function draw()
	PlayerClass.draw()
end
```

playerclass.lua
```
PlayerClass = {}
image = of.Image()
function PlayerClass.setup()
	image:loadImage('sprite/player/Player.png')
end

function PlayerClass.draw()
	image:draw(0,0)
end
```
but it still actually shows a blank window. but thanks still for the help, getting close to sorting it ;)

**Comment by danomatika** [comment]
Ok. Latest update allows you to do this:

    lua.doScript(script[currentScript], true); // change dir to current script's parent dir

**Comment by lewislepton** [comment]
thanks for the help and for the example, and excuse me for pecking your head so much ;)
