### ISSUE TITLE
Android?

### ISSUE THREAD

**Issue by Murii** [danomatika/ofxLua#29]
Hello!
Does ofxLua work on android?

**Comment by danomatika** [comment]
It should work, although it's not been tested.

**Comment by Murii** [comment]
Can I use this addon with the latest version of ofx?

Trimis de pe iPhone-ul meu

Pe 11.05.2015, la 01:13, Dan Wilcox <notifications@github.com> a scris:

**Comment by danomatika** [comment]
Yes, the latest release version. As the [readme says](https://github.com/danomatika/ofxLua#which-version-to-use):

>The master branch of ofxLua will work with the current stable version of OpenFrameworks and can be considered relatively stable.
