### ISSUE TITLE
Problem during linking with luaExample

### ISSUE THREAD

**Issue by jbltx** [danomatika/ofxLua#30]
I have a linker problem using the given example in the repo : 

``` sh
Undefined symbols for architecture x86_64:
  "of::priv::setWorkingDirectoryToDefault()", referenced from:
      _wrap_setWorkingDirectoryToDefault(lua_State*) in ofxLuaBindings.o
  "_glutDragEventFunc", referenced from:
      ofAppGlutWindow::setup(ofGLWindowSettings const&) in libopenFrameworks.a(ofAppGlutWindow.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [bin/luaExample] Error 1
make: *** [Release] Error 2
```

Is there any library I need to add somewhere during linking ?

**Comment by danomatika** [comment]
What's your OS and how are you building the example (Xcode, makefiles, etc).

**Comment by jbltx** [comment]
I tried using an auto-generated Xcode Project file in Xcode and also using make command. It was the same result. My machine is a Mac OSX 10.11.6 (El Capitan). I checked out the repo to 0.9.0.

**Comment by danomatika** [comment]
Why version of OF are you using? If it's 0.9.3, you should be using the master bench of this repo as there were some changes made to the API between 0.9.0 and 0.9.3 that the lua bindings were updated for.

I just did a test and the example is working fine for me.

**Comment by jbltx** [comment]
I will check it this evening, my mistake was maybe to checkout the repo to last tag version

**Comment by danomatika** [comment]
Any updates on this?

**Comment by danomatika** [comment]
I recently regenerated the bindings without some of the low level window access functions. This may help.

**Comment by danomatika** [comment]
Is this issue solved?

**Comment by jbltx** [comment]
Yes it solved, sorry I forgot to close it.
Thank you !
