### ISSUE TITLE
luajit-5.1 not found when compiling example on Raspberry Pi

### ISSUE THREAD

**Issue by zealtv** [danomatika/ofxLua#31]
Hello!
Thanks for your work on this - it's a great addon.

I'm having some difficulties building the luaExample on a Raspberry Pi 3 running Raspbian Jessie Lite.    When building I get this reoccurring error: 

> Package luajit-5.1 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `luajit-5.1.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'luajit-5.1' found

I'm pretty sure I have the required dependency installed:

> libluajit-5.1-2 is already the newest version.
> libluajit-5.1-common is already the newest version.
> libluajit-5.1-dev is already the newest version.

but running sudo find / -name 'luajit-5.1.pc' returns nothing.

Any hints you could offer as to what to try next?

**Comment by danomatika** [comment]
Maybe try changing luajit-5.1 to luajit-5.1.2 in the addon_config.mk? It's probably just a naming issue, although bug level versions are using symlinked the regular versions.

**Comment by danomatika** [comment]
Actually, it looks like the pig-config file is actually `luajit.pc`, so try simply "luajit" instead: https://packages.debian.org/search?mode=filename&suite=jessie&section=all&arch=any&searchon=contents&keywords=luajit.pc

**Comment by zealtv** [comment]
Thank you for the quick reply.  Changing to luajit.pc did indeed fix that build error.  
I'm now getting a string of errors stemming from this:

> /home/pi/openFrameworks/addons/ofxLua/src/ofxLua.h:506:24: error: there are no arguments to ‘lua_pushglobaltable’ that depend on a template parameter, so a declaration of ‘lua_pushglobaltable’ must be available [-fpermissive]
>    lua_pushglobaltable(L);

Currently looking in to it.

**Comment by danomatika** [comment]
I think that's a function added in lua 5.2 that luajit doesn't have as it's still using the 5.1 api. I'll whip up a check and do it the old way for 5.1.

**Comment by danomatika** [comment]
I pushed a commit that should solve both of those issues so far.

**Comment by zealtv** [comment]
Thank you!  Yes,  both of those issues are fixed with the last commit.  
Now hitting a unreferenced vtable error upon linking... looks like it might be stemming of OF itself?

> obj/linuxarmv6l/Release/src/main.o: In function `ofAppGlutWindow::~ofAppGlutWindow()':
> main.cpp:(.text._ZN15ofAppGlutWindowD2Ev[_ZN15ofAppGlutWindowD5Ev]+0x1004): undefined reference to `vtable for ofAppGlutWindow'
> obj/linuxarmv6l/Release/src/main.o: In function `ofAppGlutWindow::~ofAppGlutWindow()':
> main.cpp:(.text._ZN15ofAppGlutWindowD0Ev[_ZN15ofAppGlutWindowD5Ev]+0x1004): undefined reference to `vtable for ofAppGlutWindow'
> obj/linuxarmv6l/Release/src/main.o: In function `void ofSetupOpenGL<ofAppGlutWindow>(std::shared_ptr<ofAppGlutWindow>, int, int, ofWindowMode)':
> main.cpp:(.text._Z13ofSetupOpenGLI15ofAppGlutWindowEvSt10shared_ptrIT_Eii12ofWindowMode[_Z13ofSetupOpenGLI15ofAppGlutWindowEvSt10shared_ptrIT_Eii12ofWindowMode]+0x7fc): undefined reference to `ofAppGlutWindow::loop()'
> obj/linuxarmv6l/Release/src/main.o: In function `main':
> main.cpp:(.text.startup+0x10): undefined reference to `ofAppGlutWindow::ofAppGlutWindow()'
> /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxLua/src/bindings/linuxarm/ofxLuaBindings.o: In function `_wrap_setupOpenGL':
> ofxLuaBindings.cpp:(.text+0x26929c): undefined reference to `ofSetupOpenGL(std::shared_ptr<ofAppGLFWWindow>, int, int, ofWindowMode)'
> collect2: error: ld returned 1 exit status
> /home/pi/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:382: recipe for target 'bin/luaExample' failed
> make[1]: *** [bin/luaExample] Error 1
> make[1]: Leaving directory '/home/pi/openFrameworks/apps/myApps/luaExample'
> /home/pi/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:125: recipe for target 'Release' failed
> make: *** [Release] Error 2

**Comment by danomatika** [comment]
Which version of OF are you using? The lua bindings are kept up to date with the current *release*, not with the development version on github.

**Comment by danomatika** [comment]
The first 3 errors are probably due to calling ofSetupOpenGL() with an ofAppGlutWindow which is not available on RPI. I assume you're porting a project form desktop? You will need to change your main to match how to RPI example start things.

**Comment by danomatika** [comment]
I just pushed a commit which removes the bindings to low-level stuff like ofSetupOpenGL, which is something best left to C++ anyway.

**Comment by zealtv** [comment]
The app is now compiling happily.  I'm hitting a seg fault which I'm yet to trace - next chance I get to look at it, if it looks like a lua+pi think I'll let you know.  Thanks again for your quick help.

**Comment by danomatika** [comment]
Cool. I know it worked relatively well with luajit on an RPI 2, so it must be nice and fast on an RPI 3.
