### ISSUE TITLE
VS 2015 Compilation Error

### ISSUE THREAD

**Issue by felipetesc** [danomatika/ofxLua#33]
Hello!
I'm finding some trouble in order to compile the plugin: currently the VS give me this error message:
Error C3861	'chdir': identifier not found. When I navigate to the line 163 from the file 'ofxLua.cpp' , I find this: chdir(folder.c_str());

I searched the web and I found this interesting post:
http://stackoverflow.com/questions/3485166/change-the-current-working-directory-in-c 
There, I read chdir is  deprecated for MS, and the correct method name is _chdir. (About that, I really don't know) Thank you.

**Comment by danomatika** [comment]
Nice catch. I'll put a fix in, thank you.

**Comment by danomatika** [comment]
I just made some commits that will call _chdir on Windows. Can you do a pull and try building again?

**Comment by danomatika** [comment]
ping

**Comment by danomatika** [comment]
Can you confirm this fix?

**Comment by felipetesc** [comment]
I'll do that right away. I was little busy, but today I have time. I'll send the whereabouts...

**Comment by felipetesc** [comment]
Hi there. It seems the problem with the chdir it's ok. At least the compiler worked when building that part. However I found another small issue, on line number 936 of the file "lstrlib.c", it's located inside the "Lua". Do I open another Issue ?
