### ISSUE TITLE
pushTable error when table in another table

### ISSUE THREAD

**Issue by azuremous** [danomatika/ofxLua#34]
Hi~
I got a error when I use getStringVector function after push table for global.
I think it caused at line 532, 533 : ofxLua.cpp

lua_gettable(L, LUA_STACK_TOP);
if(!lua_istable(L, LUA_STACK_TOP))

It actually need to be 'LUA_STACK_TOP - 1' . Isn't it?

Thanks! ofxLua is really good!!!

**Comment by danomatika** [comment]
If you just need to grab the contents of a table at the global level already, you don't need to push the global table, just call getStringTable().

See the runTests() function in the luaExample app which loads a lua file and tests the data get & set functions.

**Comment by azuremous** [comment]
Global is not problem. It works. 
Problem is when I want to get the contents of another table.

ofApp.cpp

```
lua.pushTable("atable");
lua.getStringVector("stringTable",tags[0]);
```

example.lua
```
atable = {}  //grobal
atable.stringTable = { "hello", "some text", "cha cha" } 
```

And I got a this warning.
[warning] ofxLua: Couldn't push table "stringTable"

If I change line 532, 533 : ofxLua.cpp like 'LUA_STACK_TOP - 1', it works.
Thanks!

**Comment by danomatika** [comment]
Latest commit should have the fix.
