### ISSUE TITLE
Conversion problem file lstrlib.c 

### ISSUE THREAD

**Issue by felipetesc** [danomatika/ofxLua#35]
I found another small issue, on line number 936 of the file "stdlib.c", it's located inside the "Lua" folder. It belongs to Lua source itself, I've looked at the file's header, and the author's name is Roberto and it was created at 05/20/2016. Searching the internet, I've found this:  http://lua-users.org/lists/lua-l/2016-06/msg00387.html

The issue itself it's just a conversion problem inside the method witch signature is "static void checkdp (char *buff, int nb)", it's a C++ problem, I don't know if GNU G++, or a non VS C++ compiler will have the same problem.  I will investigate more, but no guarantees to find something.

**Comment by felipetesc** [comment]
After changing the line 283 of lobject.c from: 
`char *pdot = strchr(s, '.');` to `char *pdot = (char *)strchr(s, '.');`
and the line 936 lstrlib.c from `char *ppoint = memchr(buff, point, nb);` to `char *ppoint = (char *)(memchr(buff, point, nb));` the Lua compiled but now I found some other issue. I will open a new thread and bring to light.

**Comment by danomatika** [comment]
Looks like this was fixed in lua 5.3.4. Can you pull the latest commit and try building again?
