### ISSUE TITLE
misplaced statement in bool ofxLua::exists(const string& name, int type)

### ISSUE THREAD

**Issue by alexp-nl** [danomatika/ofxLua#37]
Hi Dan, 

I came across a problem in the function bool ofxLua::exists(const string& name, int type).

In line 1081 the named field that is to be tested is pushed on the stack. And in the line after that, you want to make sure that the top of the stack before this push is a table. I think you should test LUA_STACK_TOP-1. Or move line 1081 to just before 1088.

**Comment by danomatika** [comment]
Do have you sample code to illustrate that this is a bug?

**Comment by alexp-nl** [comment]
Yes, but it is embedded in a large project, so it is not very practical to send you this. 

But for instance try ofxLua::isFuction on a function in a table. Without the suggested modification you will end up in the ofLogWarning part, when the requested name in reality is a function. If you want, I can create a small example. Only not now, but later this day.

**Comment by danomatika** [comment]
I ask because I don't completely understand the Lua stack api 100%, so I'm curious why this is an issue as it *seems* to work fine. I also noticed it also seems to work fine if I change all calls within the else statement to LUA_STACK_TOP-1.

**Comment by alexp-nl** [comment]
Ok, later this day I'll try to send you a little example. But it boils down to this. The lua_getfield pushes the object on the stack that you want to test if it is a object with the requested type or not. The line after that, you want to test if the previous top of the stack is a table. But you test the current top, not the previous one.

**Comment by danomatika** [comment]
I se the issue using the read test script in luaExample and the following:

    // check if testing existance within a table works
    lua.pushTable("atable");
    ofLogNotice() << "is atable.afunction a function?: " << lua.isFunction("afunction");
    lua.popTable();

**Comment by danomatika** [comment]
Let me now if you find any other stack issues like this as I imagine there might be another somewhere.

**Comment by alexp-nl** [comment]
Thanks for the correction, I'll keep you informed if I come across other issues.

**Comment by danomatika** [comment]
This fix is also merged into the `number` branch.
