### ISSUE TITLE
How to use luajit on macOS?

### ISSUE THREAD

**Issue by cuinjune** [danomatika/ofxLua#48]
Hi @danomatika 
I'm currently trying to replace lua with luajit on macOS.
Here's how I tried to do it.

1) Download `LuaJIT-2.0.5` (current stable version)
2) Build and install it using `make && sudo make install`
3) Open a working `luaExample` project in Xcode.
4) Remove files under `addons/libs/lua` in Xcode.
5) Add `path/to/LuaJIT-2.0.5/src` to "Header Search Paths" in Xcode.
6) Add `path/to/LuaJIT-2.0.5/src` to "Library Search Paths" in Xcode.
7) Drag&drop `path/to/LuaJIT-2.0.5/src/libluajit.a` into the Xcode project.
8) If I build it, I get the following 8 errors. 

```
Undefined symbols for architecture x86_64:
  "_lua_rawlen", referenced from:
      _wrap_Arduino_sendString(lua_State*) in ofxLuaBindings.o
      _wrap_Arduino_connect__SWIG_1(lua_State*) in ofxLuaBindings.o
      _wrap_Arduino_connect__SWIG_0(lua_State*) in ofxLuaBindings.o
      _wrap_new_Directory__SWIG_1(lua_State*) in ofxLuaBindings.o
      _wrap_Directory_open(lua_State*) in ofxLuaBindings.o
      _wrap_Directory_allowExt(lua_State*) in ofxLuaBindings.o
      _wrap_Directory_copyTo__SWIG_2(lua_State*) in ofxLuaBindings.o
      ...
  "_lua_tonumberx", referenced from:
      _wrap_3dPrimitive_mapTexCoords(lua_State*) in ofxLuaBindings.o
      _wrap_3dPrimitive_drawAxes(lua_State*) in ofxLuaBindings.o
      _wrap_3dPrimitive_drawNormals__SWIG_1(lua_State*) in ofxLuaBindings.o
      _wrap_3dPrimitive_drawNormals__SWIG_0(lua_State*) in ofxLuaBindings.o
      _wrap_Arduino_sendDigitalPinMode(lua_State*) in ofxLuaBindings.o
      _wrap_Arduino_sendAnalogPinReporting(lua_State*) in ofxLuaBindings.o
      _wrap_Arduino_setDigitalHistoryLength(lua_State*) in ofxLuaBindings.o
      ...
  "_lua_pcallk", referenced from:
      ofxLua::doScript(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) in ofxLua.o
      ofxLua::scriptSetup() in ofxLua.o
      SWIG_Lua_dostring(lua_State*, char const*) in ofxLuaBindings.o
  "_lua_rotate", referenced from:
      SWIG_Lua_get_class_metatable(lua_State*, char const*) in ofxLuaBindings.o
      SWIG_Lua_namespace_get(lua_State*) in ofxLuaBindings.o
      SWIG_Lua_class_do_get(lua_State*, swig_type_info*, int, int*) in ofxLuaBindings.o
      SWIG_Lua_class_do_get_item(lua_State*, swig_type_info*, int, int*) in ofxLuaBindings.o
      SWIG_Lua_iterate_bases(lua_State*, swig_type_info*, int, int (*)(lua_State*, swig_type_info*, int, int*), int*) in ofxLuaBindings.o
      SWIG_Lua_class_do_set(lua_State*, swig_type_info*, int, int*) in ofxLuaBindings.o
      SWIG_Lua_get_inheritable_metamethods(lua_State*) in ofxLuaBindings.o
      ...
  "_lua_copy", referenced from:
      _proxy__wrap_new_3dPrimitive(lua_State*) in ofxLuaBindings.o
      _proxy__wrap_new_Arduino(lua_State*) in ofxLuaBindings.o
      _proxy__wrap_new_BoxPrimitive(lua_State*) in ofxLuaBindings.o
      _proxy__wrap_new_Buffer(lua_State*) in ofxLuaBindings.o
      _proxy__wrap_new_BufferObject(lua_State*) in ofxLuaBindings.o
      _proxy__wrap_new_Camera(lua_State*) in ofxLuaBindings.o
      _proxy__wrap_new_FloatColor(lua_State*) in ofxLuaBindings.o
      ...
  "_lua_getglobal", referenced from:
      ofxLua::scriptSetup() in ofxLua.o
      ofxLua::exists(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) in ofxLua.o
  "_lua_callk", referenced from:
      _proxy__wrap_new_3dPrimitive(lua_State*) in ofxLuaBindings.o
      _proxy__wrap_new_Arduino(lua_State*) in ofxLuaBindings.o
      _proxy__wrap_new_BoxPrimitive(lua_State*) in ofxLuaBindings.o
      _proxy__wrap_new_Buffer(lua_State*) in ofxLuaBindings.o
      _proxy__wrap_new_BufferObject(lua_State*) in ofxLuaBindings.o
      _proxy__wrap_new_Camera(lua_State*) in ofxLuaBindings.o
      _proxy__wrap_new_FloatColor(lua_State*) in ofxLuaBindings.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Do you know if I'm missing anything?
I'd appreciate if you could give me a hint to build the `luaExample` using luajit on macOS.
Thank you so much!

**Comment by danomatika** [comment]
I've not tested luajit directly.

luajit uses the Lua 5.1 API and I think you're seeing missing functions from the bindings that were generated using Lua 5.3 included with ofxLua. You will probably have to regenerate the bindings and somehow force SWIG to use Lua 5.1 only.

**Comment by cuinjune** [comment]
Added the "Library Search Paths" which reduced the number of errors from 53 to 8.

**Comment by cuinjune** [comment]
Thank you for your answer.
I could reduce the number of errors from 53 to 8 by adding the "Library Search Paths" in Xcode.
I also tried using `LuaJIT-2.1.0-beta3` but I still got 6 errors.
So I guess I need to regenerate the SWIG bindings for OF API like you said.

First of all, I could successfully generate the SWIG bindings with `make desktop LANG=lua` command.
Do you have any idea how to force SWIG to only use Lua 5.1 using your `swig-openframeworks`?

**Comment by danomatika** [comment]
What are the errors? It might be stuff I can fix. I think I was wrong about SWIG as it generates defines for different lua versions.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by cuinjune** [comment]
Please check the errors from my original post which I edited.
Also, please check if I did everything correctly.
I would really appreciate if you can fix the problem.

**Comment by danomatika** [comment]
I just tested it and am able to build a run on macOS. I installed LuaJIT from Homebrew but it should work equally well if handled manually. See https://github.com/danomatika/ofxLua/commit/ebfc5d2065208b6153779e7645604e2e6c92935a

**Comment by cuinjune** [comment]
Thank you so much for your work.
I followed your instruction and it works like a charm.

Now I need to figure out one more thing.
https://stackoverflow.com/questions/50849712/how-to-set-linker-flags-for-main-executable

You can close this issue if you want. Thank you :)
