### ISSUE TITLE
Replace Luabind with SWIG

### ISSUE THREAD

**Issue by arthursw** [danomatika/ofxLua#5]
Hi,

Congratulations for your work!
I have never used swig but I heard a lot of good things about it. I was wondering if you used it, and if we could easily and automatically generate wrappers with it.

(I don't know if this is the right place for my comments, but I can't find any other place)

Thanks!

**Comment by danomatika** [comment]
I have SWIG working with ofxLua now: check the `swig` branch.

**Comment by danomatika** [comment]
Also to note: 

1. SWIG can wrap the stl classes
2. I have class support working in ofxLua using SWIG by using a class function from the Lua wiki, see <https://github.com/danomatika/ofxLua/tree/swig#classes>. It doesn't allow you to inherit C++ classes, but I think that's a decent tradeoff for not requiring Boost, keeping track of Luabind changes, and much easier distribution of the generated .cpp bindings.
