### ISSUE TITLE
Using ofxAssimpModelLoader in ofxLua?

### ISSUE THREAD

**Issue by cuinjune** [danomatika/ofxLua#51]
Hi, Is it possible to load .obj files using ofxLua?

I think `ofxAssimpModelLoader` can do this but it's not part of OF core, right?

In this case, should I wrap this addon using SWIG? (using the new module name `ofx`?)

Thanks in advance!

**Comment by danomatika** [comment]
The ofxLua bindings are only the OF core, no addons. You'll need to write a SWIG interface and generate your own bindings for the add-on. See my [ofxOsc bindings for loaf](https://github.com/danomatika/loaf/tree/master/swig).

Also, I would avoid using "ofx" as the module name as there is no way to share the same module name between separately generated bindings.
