### ISSUE TITLE
Change v.vec2() to v:vec2() in README.md

### ISSUE THREAD

**Issue by cuinjune** [danomatika/ofxLua#52]
Hi, I just found one thing to be fixed in `README.md`

> -- convert
> of.drawRectangle(v.vec2(), 20, 20) -- ofVec2f -> glm::vec2

I think `v.vec2()` should be `v:vec2()`.

Thank you.

**Comment by danomatika** [comment]
Yes. Closed with e458b9dae6dc25c24e84849557ab9ca4ccc0bbd3.
