### ISSUE TITLE
ofFboSettings ignored?

### ISSUE THREAD

**Issue by dom1817** [danomatika/ofxLua#56]
In order to call the function getDepthTexture() I need to set the two properties "useDepth" and "depthStencilAsTexture" of the ofFbo class. 

I tried using ofFboSettings but it didn't work, as far as I can tell it is ignored in the swig files:

`114 | %ignore ofFboSettings;`
`115 | %ignore ofFbo::Settings;`
`116 | %ignore allocate(ofFboSettings);`

Is there another way to set these properties and get a depth texture using ofxLua?

**Comment by danomatika** [comment]
Quick way is to comment those ignores and re-generate the bindings with SWIG. In the meantime, I've added binding support for other settings objects, so it's probably time to support this one as well. If I recall, I think I skipped it as it's more than a simple struct and needed more time to wrap.

**Comment by danomatika** [comment]
Latest commit adds ofFboSettings struct bindings.
