### ISSUE TITLE
error getting unique faces from 3D primitive 

### ISSUE THREAD

**Issue by owenosborn** [danomatika/ofxLua#61]
I'm working on some of the stuff in the OF 3D primitives example.  Stuck on getting vector of triangles from a mesh.  Running this:

    local icoSphere = of.IcoSpherePrimitive()
    local mesh = icoSphere:getMesh()
    local triangles = mesh:getUniqueFaces()

I was expecting a wrapped vector to be returned. Instead I get error:

    attempt to index local 'mesh' (a userdata value)

Is this expected?  I'm a little new to lua so I don't know if I'm missing something...

**Comment by danomatika** [comment]
`icoSphere:getMesh()` should work. You can print detailed type info for objects wrapped by swig using the special `swig_type` (not native to Lua, but added by SWIG).

Getting ofMeshFace vector probably won't work as I missed wrapping it, so you will get a correct userdata type except the bindings are missing and Lua won't know what to do with it. "user data" basically means it's a pointer to something and it's up to the bindings to handle working with it.

I've just added a wrapper for std::vector<ofMeshFace_...> for ofxLua 1.4.1, so the following works for me:

```lua
  local icoSphere = of.IcoSpherePrimitive()
  local icoMesh = icoSphere:getMesh()
  print("icoMesh vertices: "..tostring(icoMesh:getNumVertices()))
  local icoVertices = icoMesh:getVertices()
  print("icoVertices is "..swig_type(icoVertices))
  print("  number of vertices: "..tostring(icoVertices:size()))
  icoMesh:setMode(of.PRIMITIVE_TRIANGLES)
  local icoTriangles = icoMesh:getUniqueFaces()
  print("icoTriangles is "..swig_type(icoTriangles))
  print("  number of triangles: "..tostring(icoTriangles:size()))
```

prints

~~~
icoMesh vertices: 354.0
icoVertices is std::vector< glm::vec3 > *|std::vector< ofDefaultVertexType > *|std::vector< ofDefaultNormalType > *
  number of vertices: 354.0
icoTriangles is std::vector< ofMeshFace_< ofDefaultVertexType,ofDefaultNormalType,ofDefaultColorType,ofDefaultTexCoordType > > *
  number of triangles: 320.0
~~~

If you need to stay with OF 0.10 and ofxLua 1.3, then you will need to cherry-pick or manually add the relevant SWIG %template line to the bindings in the `ofxLua/swig` directory: https://github.com/danomatika/swig-openframeworks/commit/8f2f68955b7a70ae50b8f61a82e1e4001834b7e6#diff-7fedcf9017c481bca1f35dc3ce350b6cR30

Once you update that, regenerate the bindings by installing SWIG and running `scripts/generate_bindings.sh`.

**Comment by owenosborn** [comment]
I rebuilt newest OF (0.11.0) and ofxLua (1.4.1) and it is all working now.  Thanks!

Also thanks for the tip about swig_type, that is very helpful to know.

**Comment by danomatika** [comment]
>Also thanks for the tip about swig_type, that is very helpful to know.

I've now added this to the readme as well.
