### ISSUE TITLE
Compile error on pi3b+ ofxLuaBindings

### ISSUE THREAD

**Issue by okyeron** [danomatika/ofxLua#62]
Just getting started with OF and trying to get ofxLua compiled.

I copied the luaExample to myApps and then copied the `Makefile` and `config.make` from emptyExample to luaExample.

on `make` I'm getting the following error:

```
/home/we/openFrameworks/addons/ofxLua/src/bindings/linuxarm/ofxLuaBindings.cpp: At global scope:
/home/we/openFrameworks/addons/ofxLua/src/bindings/linuxarm/ofxLuaBindings.cpp:16363:12: warning: ‘int _wrap_3dPrimitive_draw(lua_State*)’ defined but not used [-Wunused-function]
 static int _wrap_3dPrimitive_draw(lua_State* L) { int SWIG_arg = 0; of3dPrimitive *arg1 = (of3dPrimitive *) 0 ;
            ^~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [/home/we/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:360: /home/we/openFrameworks/addons/obj/linuxarmv6l/Release/ofxLua/src/bindings/linuxarm/ofxLuaBindings.o] Error 1
make[1]: Leaving directory '/home/we/openFrameworks/apps/myApps/luaExample'
make: *** [/home/we/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:129: Release] Error 2
```

I tried this with the current version of ofxLua and then tried checking out 1.3.0 instead. On the current release, the compile freezes at this stage with the Pi's disk activity led on full. On 1.3.0, it errors with the above.

This is a Raspberry Pi 3b+ with Buster (4.19.66-v7+), gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1). OF 0.11.0

**Comment by okyeron** [comment]
Followup... it appears I did not run the `generate_bindings.sh` script

Note - this has a dependency of SWIG which is not otherwise installed on Raspberry Pi. 

Was just able to compile on my pi4 (same system version 4.19.66-v7+) - so I guess that solves it.

Adding documentation about the SWIG dependency would be nice.

**Comment by danomatika** [comment]
SWIG is not a direct dependency as the generated bindings are already provided with ofxLua. This is is why you were able to start compiling *before* using SWIG, ie. `src/bindings/linuxarm/ofBindings.cpp` already exists.

**Comment by danomatika** [comment]
>I tried this with the current version of ofxLua and then tried checking out 1.3.0 instead.

Also, versions of ofxLua are matched to existing OF versions as the API may change. As listed [in the changelog](https://github.com/danomatika/ofxLua/blob/master/CHANGES.txt#L61), ofxLua 1.3.0 provides bindings for OF  0.10, so it may not build using OF 0.11.

Which version of OF are you using?

Additionally, I just pushed a commit I forgot about, can you try that if you are using OF 0.11? If it the current `master` branch including this new commit doesn't build, can you regenerate the bindings and include a diff or a copy of `src/bindings/linuxarm/ofBindings.cpp` here?

**Comment by okyeron** [comment]
Everything was pulled from the master/main repos yesterday. So newest versions of OF (0.11.0) and ofxLua.

Testing from my pi3b+ just now
- added swig with `sudo apt-get install swig`
- git pull on ofxLua
- ran `./scripts/generate_bindings.sh`
- did `make clean` on my app
- did `make`
- stalled again at `_wrap_3dPrimitive_draw` with disk activity full on

ofBindings.cpp: [ofBindings.cpp.zip](https://github.com/danomatika/ofxLua/files/5543911/ofBindings.cpp.zip)

Newly generated bindings were identical to the previous ones.

**Comment by okyeron** [comment]
FWIW - I don't see any new commits today in the master branch.

But I removed ofxLua and started over. Still stalled in the same place (tried to login from another ssh window and could not login until I cntrl-C'd the make process)

NOw I have a diff between the previous and new ofBindings.cpp:
```
Nonmatching Lines (File ofBindings_new.cpp; Line 2778:2899; File ofBindings_old.cpp; Line 2778:2896)
Extra lines in New before 17682 in Old (File ofBindings_new.cpp; Line 17685:17828; File ofBindings_old.cpp; Line 17682)
Extra lines in New before 49036 in Old (File ofBindings_new.cpp; Line 49183:49190; File ofBindings_old.cpp; Line 49036)
Extra lines in New before 49796 in Old (File ofBindings_new.cpp; Line 49951; File ofBindings_old.cpp; Line 49796)
Extra lines in New before 49884 in Old (File ofBindings_new.cpp; Line 50040:50045; File ofBindings_old.cpp; Line 49884)
Extra lines in New before 50212 in Old (File ofBindings_new.cpp; Line 50374:50376; File ofBindings_old.cpp; Line 50212)
Extra lines in New before 50345 in Old (File ofBindings_new.cpp; Line 50510:50511; File ofBindings_old.cpp; Line 50345)
Extra lines in New before 50409 in Old (File ofBindings_new.cpp; Line 50576; File ofBindings_old.cpp; Line 50409)
Extra lines in New before 50606 in Old (File ofBindings_new.cpp; Line 50774:50776; File ofBindings_old.cpp; Line 50606)
Extra lines in New before 50739 in Old (File ofBindings_new.cpp; Line 50910:50911; File ofBindings_old.cpp; Line 50739)
Extra lines in New before 50803 in Old (File ofBindings_new.cpp; Line 50976; File ofBindings_old.cpp; Line 50803)
```

new bindings: 
[ofBindings_new.cpp.zip](https://github.com/danomatika/ofxLua/files/5544050/ofBindings_new.cpp.zip)

**Comment by okyeron** [comment]
Hi Dan,

Circling back on this trying to complile my project on the pi3b+ again.

> Also, I just pushed a commit I forgot about, can you try that if you are using OF 0.11?

Can you send me that change to test (I don't see any recent commits here)? Or let me know if there's anything else I can try?

Does my lua version matter here?

**Comment by danomatika** [comment]
Looking at this again, I don't see anything obvious that should really be causing an issue. The 3dPrimitive base class is wrapped so the subclasses (ofBoxPrimitive, etc) call all the baseclasess's member functions. I was thinking that we can ignore it, but that breaks the subclasses as is probably "treating the symptom" as opposed to fixing the underlying cause.

As for the commits I was referring to before, I'm not sure. I don't see anything newer than Aug 31st which was the last time I was working on this.

**Comment by okyeron** [comment]
Trying again with the updates from today and still freezing up. Doing a full fresh reinstall of OF 0.11.0 and ofxLua now and will try once more.

FWIW - could this be some gcc version related problem? I get a tonne of warnings while compiling.

my gcc version info:
```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/8/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 8.3.0-6+rpi1' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --disable-libquadmath-support --enable-plugin --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --disable-werror --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1) 
```

**Comment by danomatika** [comment]
No idea. I've only built ofxLua for macOS and iOS myself.

**Comment by okyeron** [comment]
Interesting development...

I did a completely fresh build with a recent Raspberry PI OS version (one version back from current - 5.4.79-v7+). Fresh install of OF and ofxLua, etc. and then still no luck.

Searching on the forums I came across someone else with a different compile problem where they solved it by increasing the swap memory.

So I tried this and it worked!

Apparently the pi3b+ doesn't have quite enough memory to deal with the big bindings compile? Increasing the swap to 1024 got me sorted. This also likely explains why the pi4 worked OK as it has more memory.

Not sure if there are some compile flags that would help with this. I may ask on the forum when I get some time.

Just to document this for future reference, on the pi3b+ I needed to first install dphys-swapfile

`sudo apt install dphys-swapfile`

then edit  /etc/dphys-swapfile 

`sudo nano /etc/dphys-swapfile`

un-commenting and setting `CONF_SWAPFILE=/var/swap`, `CONF_SWAPSIZE=1024` and `CONF_MAXSWAP=2048`

Then save and reboot.

**Comment by danomatika** [comment]
That makes sense. Too bad gcc can't give you a better error. In any case, I've added this info to the readme: f229813b7f2688d1604c23ca9e11967fca527445

It's probably become an issue as the bindings have grown since the first SWIG wrapper. I did not intend to wrap the OF API 100% but the requests for more and more support keep rolling in while new OF versions don't seem to be removing much.
