### ISSUE TITLE
getErrorMessage() is not defined anymore

### ISSUE THREAD

**Issue by Ant1r** [danomatika/ofxLua#67]
https://github.com/danomatika/ofxLua/blob/ff8e1485d20e88f65577ebfa9bfa940986f3f77e/src/ofxLua.h#L455

In the past it was:
```C++
std::string getErrorMessage() {return errorMessage;}
```
I've just tried restoring this and it works well.

**Comment by danomatika** [comment]
Did it get removed somewhere? I don't have build errors in any of my projects...

**Comment by Ant1r** [comment]
I think if you don't call it (e.g you're using callbacks) then the error isn't thrown?

**Comment by danomatika** [comment]
Fixed in latest commit and new 1.4.5 bugfix version.

**Comment by danomatika** [comment]
I didn't notice it since I used the error callback instead of the string in [loaf](https://github.com/danomatika/loaf) which is my main usage for ofxLua.
