### ISSUE TITLE
fails to compile on Arch (Manjaro) due to Boost version?

### ISSUE THREAD

**Issue by Newk77** [danomatika/ofxLua#68]
Hi,
i tried to compile the luaExample and [it runs into issues](https://pastebin.com/WhUgVGjT)

i needed your ofxLua within Ofelia and discussed what might be wrong [there](https://github.com/cuinjune/Ofelia/issues/78) first, if you want to read up what went before getting to the conclusion, that the version difference between Boost 1.74 (ubuntu) and 1.81 (arch) might be the culprit

**Comment by danomatika** [comment]
This should be fixed with the updated bindings for OF 0.12. I will close for now but please reopen if there is still a problem.
