### ISSUE TITLE
of::filesystem::path

### ISSUE THREAD

**Issue by dimitre** [danomatika/ofxLua#70]
Hello @danomatika thanks for this great addon!
OF now adopted the of::filesystem::path which includes the supported version of filesystem (c++17, experimental, v1, boost) and I believe boost will be removed from core at some point.
I'm wondering if that can be updated here, or if your addon depends on Boost for some reason.

**Comment by danomatika** [comment]
I am aware. I don’t update the bindings until a new official OF release. Is 0.12 out now?

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by Jonathhhan** [comment]
Its out now :)

**Comment by danomatika** [comment]
Cool, thanks for the update. Hopefully I don't have to go through the whole API again like with the OF 10 -> 11 transition.

**Comment by Jonathhhan** [comment]
Already tried to recreate the bindings and `operator of::filesystem::path()` seems to cause some issues: https://stackoverflow.com/questions/10296932/what-is-warning-503-by-swig

**Comment by danomatika** [comment]
Basically, either `boost::filesystem::path` or `std::filesystem::path` is wrapped to `of::filesystem::path` in `ofConstants.h`. The bindings were last updated to wrap `boost::filesystem::path` into the language string type.

**Comment by Jonathhhan** [comment]
@danomatika I think wrapping to `of::filesystem::path` into the language string type would be great, because it does not need any adjustment. But better wait for another opinion...

**Comment by danomatika** [comment]
It is as simple as renaming the namespace in std_filesystem_path.i. SWIG keeps generating a wrapper for `v1::path` on my system which is leading to build errors, so I need to have it ignored. Almost there.

**Comment by danomatika** [comment]
Ok, I have fixes for the `filesystem::path` and the ofColor extern typedef errors in the `openframeworks-swig` repo. To test:
~~~
cd swig
git pull
cd -
scripts/generate_bindings.sh
~~~
Then rebuild whatever app you are testing.

I haven't pushed changes to the ofxLua yet as I want to check over the oF API and add any relevant changes to the bindings.

**Comment by Jonathhhan** [comment]
@danomatika thanks. The filesystem does work now (tested with ofxOfelia and OF nightly).

**Comment by danomatika** [comment]
I have updated both the bindings for OF 0.12  and Lua to 5.4.6. The new ofxLua version tag is 1.5.0.
