### ISSUE TITLE
ostringstream instead of stringstream

### ISSUE THREAD

**Issue by Jonathhhan** [danomatika/ofxLua#72]
The swig generated `ofBindings.cpp` has `ostringstream` instead of `stringstream`. It works fine after renaming.

**Comment by danomatika** [comment]
It's nice to have a solution... but it would be good to know what the actual problem is, ie. build errors on Windows, etc.

**Comment by danomatika** [comment]
This should be fixed in current master. Let me know the details of why it didn't work so  I can update the changelog.

**Comment by Jonathhhan** [comment]
Yes, it is solved in the current master...

**Comment by danomatika** [comment]
The new 1.5.1 bugfix version incorporates these changes.
