### ISSUE TITLE
luaExample Visual Studio getAsTimespec()

### ISSUE THREAD

**Issue by Jonathhhan** [danomatika/ofxLua#75]
If I compile the luaExample with Visual Studio and OF 12.0 I get this error:
`"Class "ofTime"" has no member ""getAsTimespec"".`
I guess, that is because of:
```
#ifndef TARGET_WIN32
	timespec getAsTimespec() const;
#endif
```
In `ofUtils.h`.

If I delete the `getAsTimespec` definition in ofBindings, it works:
```
static int _wrap_Time_getAsTimespec(lua_State* L) { { int SWIG_arg = 0; ofTime *arg1 = (ofTime *) 0 ; timespec result;
    SWIG_check_num_args("ofTime::getAsTimespec",1,1)
    if(!SWIG_isptrtype(L,1)) SWIG_fail_arg("ofTime::getAsTimespec",1,"ofTime const *");
    if (!SWIG_IsOK(SWIG_ConvertPtr(L,1,(void**)&arg1,SWIGTYPE_p_ofTime,0))){
      SWIG_fail_ptr("Time_getAsTimespec",1,SWIGTYPE_p_ofTime); }  result = ((ofTime const *)arg1)->getAsTimespec(); {
      timespec * resultptr = new timespec(result); SWIG_NewPointerObj(L,(void *) resultptr,SWIGTYPE_p_timespec,1); SWIG_arg++; }
     return SWIG_arg; fail: SWIGUNUSED; }  lua_error(L); return 0; }

```
`{ "getAsTimespec", _wrap_Time_getAsTimespec},`

But I wonder, if there is a smarter way to exclude this for Windows.
Compiled with OF master branch I get a lot more errors with VS, but with Linux (make) and Emscripten it works fine (I know and understand that I only have to expect the OF main release to work with ofxLua).

**Comment by danomatika** [comment]
The define probably needs to be set in your build system, then the function is not available. Check which defines are there.

**Comment by Jonathhhan** [comment]
@danomatika thanks. Define it in `addon_config.make`? I generated the VS solution with the OF project generator.

**Comment by danomatika** [comment]
Check what is set in your Visual Studio solution file in VS itself. I don't remember offhand where it is in the settings, something like Project Settings -> etc. Just look online where to set CFLAGS.

**Comment by Jonathhhan** [comment]
I know where to set VS CFLAGS. just not sure what do define (it seems `getAsTimespec` needs to be excluded from ofBindings.cpp for Windows somehow).

Out of couriosity it managed to compile the luaExample with VS and OF master and it worked after a few changes. In addition to `getAsTimespec` I had to delete all `swig_Arduino_attributes` in `ofBindings.cpp` and uncomment `#include "ofMatrix3x3.h"` in `ofVectorMath.h`.

**Comment by danomatika** [comment]
You're not sure which define? Is it not ` TARGET_WIN32`?
~~~
#ifndef TARGET_WIN32
	timespec getAsTimespec() const;
#endif
~~~
Assuming this is defined, the `getAsTimespec()` function will not be declared, effectively doing what you did to get it to compile... removing/ignoring it.

**Comment by danomatika** [comment]
AH wait, I see. It needs to be set when generating the bindings. Sorry, I was thinking it was not building due to the define not bing set at build time.

**Comment by danomatika** [comment]
Honestly, we can just ignore it. It's a low-level, language-specific thing and probably doesn't need to be in the bindings. If we *really* want to support it, I have to move the deinfe handling into the Swig interface file due to the way it's done in the C++ header. Not really worth it IMO.

The latest commit to ofxLua remove this form the bindings.

**Comment by Jonathhhan** [comment]
@danomatika thanks.
